### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by sl4mmer** [khalilbijjou/WAFNinja#1]
```
Traceback (most recent call last):                                                                                                                                                              |
  File "wafninja.py", line 58, in <module>
    firePayload(type, payload, url, post, header, delay, outputFile)
  File "/Users/dirty/Documents/Projects/WAFNinja/ninja/bypass.py", line 77, in firePayload
    occurence = content.find(payload)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 257: ordinal not in range(128)
```

**Comment by khalilbijjou** [comment]
Thanks, I will look into it.

**Comment by sl4mmer** [comment]
@khalilbijjou by the way - thanks for the great report at Positive Hack Days, last week in Moscow =)

**Comment by khalilbijjou** [comment]
The Bug should be fixed now and additional functionality has been added (proxy support, etc.)

@sl4mmer it was a pleasure for me.
