### ISSUE TITLE
WAFNinja wont work

### ISSUE THREAD

**Issue by GOD0022** [khalilbijjou/WAFNinja#13]
Hey
This the command i am trying to process

──(kali㉿kali)-[~/Desktop/WAFNinja]
└─$ python wafninja.py --help                                 
Traceback (most recent call last):
  File "wafninja.py", line 15, in <module>
    from ninja.bypass import firePayload
  File "/home/kali/Desktop/WAFNinja/ninja/bypass.py", line 16, in <module>
    from prettytable import PrettyTable
ImportError: No module named prettytable

i tried doing pip install prettytable and progressbar but none of them working pls someone help what this module thing is?and also someone pls help me on how to import prettytable

**Comment by hamo0ody** [comment]
`python2 -m pip install -r requirements.txt`

`python2 wafninja.py --version`

**Comment by Ugroon** [comment]
─# python2 -m pip install -r requirements.txt                                                                                                                                                                                         1 ⨯
/usr/bin/python2: No module named pip

**Comment by Ugroon** [comment]
pip install -r requirements.txt                                                                                                                                                                                                    1 ⨯
Requirement already satisfied: prettytable==0.7.2 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (0.7.2)
Collecting progressbar==2.3
  Using cached progressbar-2.3.tar.gz (9.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xc6_yeus/progressbar_d8937567e19d48d18726cffec7521b15/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xc6_yeus/progressbar_d8937567e19d48d18726cffec7521b15/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rbuydzy3                                                                                                                                                                                                                             
         cwd: /tmp/pip-install-xc6_yeus/progressbar_d8937567e19d48d18726cffec7521b15/                                                                                                                                                      
    Complete output (11 lines):                                                                                                                                                                                                            
    Traceback (most recent call last):                                                                                                                                                                                                     
      File "<string>", line 1, in <module>                                                                                                                                                                                                 
      File "/tmp/pip-install-xc6_yeus/progressbar_d8937567e19d48d18726cffec7521b15/setup.py", line 5, in <module>                                                                                                                          
        import progressbar                                                                                                                                                                                                                 
      File "/tmp/pip-install-xc6_yeus/progressbar_d8937567e19d48d18726cffec7521b15/progressbar/__init__.py", line 59, in <module>                                                                                                          
        from progressbar.widgets import *                                                                                                                                                                                                  
      File "/tmp/pip-install-xc6_yeus/progressbar_d8937567e19d48d18726cffec7521b15/progressbar/widgets.py", line 121, in <module>                                                                                                          
        class FileTransferSpeed(Widget):                                                                                                                                                                                                   
      File "/usr/lib/python3.9/abc.py", line 85, in __new__                                                                                                                                                                                
        cls = super().__new__(mcls, name, bases, namespace, **kwargs)                                                                                                                                                                      
    ValueError: 'format' in __slots__ conflicts with class variable                                                                                                                                                                        
    ----------------------------------------                                                                                                                                                                                               
WARNING: Discarding https://files.pythonhosted.org/packages/0f/e1/f30b72ecabba259c7c38dd0eb944a173effced3fd7de2c9c2902bd6f649a/progressbar-2.3.tar.gz#sha256=b2d38a729785149e65323381d2e6fca0a5e9615a6d8bcf10bfa8adedfc481254 (from https://pypi.org/simple/progressbar/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.                                                                                                   
ERROR: Could not find a version that satisfies the requirement progressbar==2.3
ERROR: No matching distribution found for progressbar==2.3

**Comment by kirov70** [comment]
I'm having the same issue. It seems to be an incompatibility with python3. It looks like the code needs to be updated to run with python3, but I'm not a developer.

**Comment by MrPancakes39** [comment]
Get file: ```curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py```
Install pip2: ```sudo python2 get-pip.py```
Install requirements: ```pip2 install -r requirements.txt```
Run script: ```python2 wafninja.py --version```

**Comment by huc-serverlow** [comment]
[✗]─[huc-serverlow@parrot]─[~/Downloads/WAF-Bypasser--WAFNinja-master]
└──╼ $python wafninja.py
  File "/home/huc-serverlow/Downloads/WAF-Bypasser--WAFNinja-master/wafninja.py", line 84
    print "Database sucessfully changed!"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Database sucessfully changed!")?

**Comment by TofuWand** [comment]
> [✗]─[huc-serverlow@parrot]─[~/Downloads/WAF-Bypasser--WAFNinja-master] └──╼ $python wafninja.py File "/home/huc-serverlow/Downloads/WAF-Bypasser--WAFNinja-master/wafninja.py", line 84 print "Database sucessfully changed!" ^ SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Database sucessfully changed!")?

This is what I got, too.

Using python or python3, I get this:
![Uploading Screenshot 2023-11-24 131134.png…]()

File "/home/kalimatrix/WAFNinja/wafninja.py", line 84
    print "Database sucessfully changed!"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by TofuWand** [comment]
> [✗]─[huc-serverlow@parrot]─[~/Downloads/WAF-Bypasser--WAFNinja-master] └──╼ $python wafninja.py File "/home/huc-serverlow/Downloads/WAF-Bypasser--WAFNinja-master/wafninja.py", line 84 print "Database sucessfully changed!" ^ SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Database sucessfully changed!")?

This is what I got, too.

Using python or python3, I get this:
<img width="960" alt="Screenshot 2023-11-24 131134" src="https://github.com/khalilbijjou/WAFNinja/assets/117850518/9bf55fb3-d1e0-4cbb-bdb7-1e0b907ad44a">

File "/home/kalimatrix/WAFNinja/wafninja.py", line 84
    print "Database sucessfully changed!"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by TofuWand** [comment]
> Get file: `curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py` Install pip2: `sudo python2 get-pip.py` Install requirements: `pip2 install -r requirements.txt` Run script: `python2 wafninja.py --version`

Even with what you suggested, I'm still getting issues. Thanks anyways though.
![Screenshot_2024-02-23_13_24_48](https://github.com/khalilbijjou/WAFNinja/assets/117850518/ae08c83b-b432-44e0-a935-e1ff4d1e2234)
