### ISSUE TITLE
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>

### ISSUE THREAD

**Issue by filebe777** [khalilbijjou/WAFNinja#8]
Fuzz Scanning Starting                       ║
╚════════════════════════════════════════════════════════════════╝
starting fuzzing with waf ninja

    ___       ______________________   ______       ________        
    __ |     / /__    |__  ____/__  | / /__(_)____________(_)_____ _
    __ | /| / /__  /| |_  /_   __   |/ /__  /__  __ \____  /_  __ `/
    __ |/ |/ / _  ___ |  __/   _  /|  / _  / _  / / /___  / / /_/ / 
    ____/|__/  /_/  |_/_/      /_/ |_/  /_/  /_/ /_/___  /  \__,_/  
                                                    /___/           
                                                    
    WAFNinja - Penetration testers favorite for WAF Bypassing
    
Traceback (most recent call last):#################################  |
  File "wafninja.py", line 67, in <module>
    fireFuzz(type, fuzz, url, post, header, delay, outputFile, proxy, prefix, postfix)
  File "/home/user/Desktop/Yuki-Chan-The-Auto-Pentest/Module/WAFNinja/ninja/fuzzer.py", line 89, in fireFuzz
    response = opener.open(url_with_fuzz)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>
fuzzing finished

**Comment by khalilbijjou** [comment]
Could you please add the full command you used?

**Comment by filebe777** [comment]
i did not run it alone, i ran it from.....

https://github.com/Yukinoshita47/Yuki-Chan-The-Auto-Pentest

**Comment by teodem** [comment]
I've the same issue
